### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [Drewdubeast/QRKit#2]
```
let vc = QRRead()
self.navigationController?.pushViewController(vc, animated: true)
```
fails on the following line:
```
view.bringSubview(toFront: bottomScannerBar)
```

**Comment by Drewdubeast** [comment]
@gerchicov-bp I am aware of those issues! I honestly just took out the QR reading until I can actually get it working. Right now, I have just the QR generation, easy stuff, but this is really just meant to help people who barely know Swift at all.
